server:
  port: 8080
spring:
  application:
    name: service-user
  cloud:
    nacos:
      server-addr: 43.143.139.24:8848
      username: nacos
      password: songyang.top@@##$$
  datasource:
    username: root
    password: songyang.top@@##$$
    url: jdbc:mysql://43.143.139.24:3306/yiran
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl