server:
  port: 8083
spring:
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 43.143.139.24:8848
      username: nacos
      password: songyang.top@@##$$
    sentinel:
      transport:
        dashboard: localhost:8000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.143.139.24:3306/yiran
    username: root
    password: songyang.top@@##$$
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  sentinel:
    enabled: true