server:
  port: 2177
spring:
  application:
    name: yiran-gateway
  cloud:
    nacos:
      server-addr: 43.143.139.24:8848
      username: nacos
      password: songyang.top@@##$$
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心路由功能
      routes:
        - id: 1
          uri: lb://service-order
          predicates:
            - Path=/order/**

